"use client"

import { useCallback, useEffect, useMemo, useState } from "react"
import { AlertTriangle, ArrowRight, BarChart3, CalendarDays, CheckCircle2, ClipboardList, Gauge, RefreshCw, Send, TrendingUp } from "lucide-react"
import Link from "next/link"
import { AppShell } from "@/components/app-shell"
import { EmptyState, StatusBadge } from "@/components/product-ui"
import { useAuth } from "@/components/auth-context"

type Tendencia = { data: string; respostas: number }
type Resumo = { respostas: number; campanhas: number; convites: number; media: string | number; taxa_resposta: string | number; tendencia: Tendencia[] }
type Campanha = { id: number; nome: string; status: string; encerraEm?: string; versao?: { numero: number; questionario?: { nome: string } }; setores?: { id: number; nome: string }[]; indicadores: { convites: number; respondidas: number; taxaResposta: number } }
type Setor = { id: number; nome: string }
const button = "inline-flex items-center justify-center gap-2 rounded-xl px-3.5 py-2.5 text-sm font-semibold transition focus:outline-none focus:ring-4 focus:ring-[#c99176]/25"

export default function DashboardPage() {
  const { token, logout } = useAuth()
  const [resumo, setResumo] = useState<Resumo | null>(null)
  const [campanhas, setCampanhas] = useState<Campanha[]>([])
  const [setores, setSetores] = useState<Setor[]>([])
  const [campanhaId, setCampanhaId] = useState("")
  const [setorId, setSetorId] = useState("")
  const [periodo, setPeriodo] = useState("30")
  const [loading, setLoading] = useState(true)
  const [erro, setErro] = useState("")
  const api = useCallback(async (path: string) => { const response = await fetch(`/api/backend${path}`, { headers: { Authorization: `Bearer ${token}` } }); const data = await response.json().catch(() => ({})); if (response.status === 401) { logout(); throw new Error("Sua sessão expirou. Entre novamente.") } if (!response.ok) throw new Error(data.message || "Não foi possível carregar os dados"); return data }, [logout, token])
  const query = useMemo(() => { const params = new URLSearchParams(); if (campanhaId) params.set("campanhaId", campanhaId); if (setorId) params.set("setorId", setorId); if (periodo !== "todos") { const inicio = new Date(); inicio.setDate(inicio.getDate() - Number(periodo)); params.set("inicio", inicio.toISOString().slice(0, 10)) } const value = params.toString(); return value ? `?${value}` : "" }, [campanhaId, periodo, setorId])
  const carregar = useCallback(async () => { if (!token) return; setLoading(true); try { const [resumoData, campanhasData, setoresData] = await Promise.all([api(`/relatorios/resumo${query}`), api("/campanhas"), api("/setores")]); setResumo(resumoData.data); setCampanhas(campanhasData.data || []); setSetores(setoresData.data || []); setErro("") } catch (error) { setErro(error instanceof Error ? error.message : "Erro ao carregar a visão geral") } finally { setLoading(false) } }, [api, query, token])
  useEffect(() => { void carregar() }, [carregar])
  const ativas = campanhas.filter((campanha) => campanha.status === "ATIVA")
  const alertas = ativas.filter((campanha) => campanha.indicadores.convites > 0 && campanha.indicadores.taxaResposta < 30).slice(0, 3)
  const maiorTendencia = Math.max(...(resumo?.tendencia || []).map((item) => item.respostas), 1)
  const metrics = resumo ? [{ label: "Campanhas ativas", value: ativas.length, detail: `${resumo.campanhas} com respostas no recorte`, icon: Send, color: "bg-[#fff1e9] text-[#7a4937]" }, { label: "Respostas recebidas", value: resumo.respostas, detail: "No período selecionado", icon: ClipboardList, color: "bg-emerald-50 text-emerald-700" }, { label: "Taxa de resposta", value: `${resumo.taxa_resposta}%`, detail: `${resumo.convites} convites gerados`, icon: Gauge, color: "bg-sky-50 text-sky-700" }, { label: "Média das escalas", value: resumo.media, detail: "Apenas perguntas numéricas", icon: TrendingUp, color: "bg-violet-50 text-violet-700" }] : []

  return <AppShell><div className="mx-auto max-w-7xl space-y-7"><section className="rounded-3xl border border-[#e6e9f0] bg-white p-6 shadow-[0_12px_32px_rgba(23,32,51,0.05)] lg:p-8"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="eyebrow">Visão executiva</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-[#172033]">O que precisa da sua atenção?</h1><p className="mt-3 max-w-2xl leading-6 text-[#687086]">Acompanhe a adesão das campanhas e descubra onde agir antes do fechamento.</p></div><Link href="/campanhas" className={`${button} bg-[#5d3a2e] text-white hover:bg-[#4e3026]`}><Send className="size-4" />Nova campanha</Link></div></section>
    <section className="surface p-4"><div className="flex flex-wrap items-center gap-3"><div className="mr-auto"><p className="text-sm font-semibold text-[#172033]">Filtros de resultados</p><p className="mt-0.5 text-xs text-[#8a92a4]">Aplicados aos indicadores e evolução.</p></div><select value={periodo} onChange={(event) => setPeriodo(event.target.value)} className="h-10 rounded-xl border border-[#d9deea] bg-white px-3 text-sm text-[#344054]"><option value="7">Últimos 7 dias</option><option value="30">Últimos 30 dias</option><option value="90">Últimos 90 dias</option><option value="todos">Todo o período</option></select><select value={setorId} onChange={(event) => setSetorId(event.target.value)} className="h-10 rounded-xl border border-[#d9deea] bg-white px-3 text-sm text-[#344054]"><option value="">Todos os setores</option>{setores.map((setor) => <option key={setor.id} value={setor.id}>{setor.nome}</option>)}</select><select value={campanhaId} onChange={(event) => setCampanhaId(event.target.value)} className="h-10 max-w-52 rounded-xl border border-[#d9deea] bg-white px-3 text-sm text-[#344054]"><option value="">Todas as campanhas</option>{campanhas.map((campanha) => <option key={campanha.id} value={campanha.id}>{campanha.nome}</option>)}</select><button onClick={() => void carregar()} disabled={loading} className={`${button} border border-[#d9deea] bg-white text-[#344054] hover:bg-[#f3f5f8]`}><RefreshCw className={`size-4 ${loading ? "animate-spin" : ""}`} /><span className="hidden sm:inline">Atualizar</span></button></div></section>
    {erro && <div role="alert" className="rounded-2xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800">{erro}</div>}
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.map((metric) => <article key={metric.label} className="surface p-5"><div className="flex items-start justify-between"><div><p className="text-sm font-medium text-[#687086]">{metric.label}</p><p className="mt-3 text-3xl font-semibold tracking-tight text-[#172033]">{loading ? "..." : metric.value}</p><p className="mt-2 text-xs text-[#8a92a4]">{metric.detail}</p></div><div className={`rounded-xl p-2.5 ${metric.color}`}><metric.icon className="size-5" /></div></div></article>)}</section>
    <div className="grid gap-6 xl:grid-cols-[minmax(0,1.5fr)_minmax(300px,.8fr)]"><section className="surface p-5 lg:p-6"><div className="flex items-start justify-between gap-4"><div><h2 className="font-semibold text-[#172033]">Evolução de respostas</h2><p className="mt-1 text-sm text-[#687086]">Quantidade diária no período selecionado.</p></div><BarChart3 className="size-5 text-[#8b5a46]" /></div>{resumo?.tendencia.length ? <div className="mt-7 flex h-52 items-end gap-2">{resumo.tendencia.slice(-14).map((item) => <div key={item.data} className="group flex min-w-0 flex-1 flex-col items-center gap-2"><div title={`${item.respostas} respostas em ${new Date(`${item.data}T12:00:00`).toLocaleDateString("pt-BR")}`} className="w-full rounded-t-lg bg-[#c99176] transition hover:bg-[#5d3a2e]" style={{ height: `${Math.max(8, (item.respostas / maiorTendencia) * 168)}px` }} /><span className="text-[10px] text-[#8a92a4]">{new Date(`${item.data}T12:00:00`).toLocaleDateString("pt-BR", { day: "2-digit", month: "2-digit" })}</span></div>)}</div> : <div className="mt-5"><EmptyState title="Ainda não há evolução para mostrar" description="As respostas recebidas aparecerão aqui ao longo do tempo." /></div>}</section>
      <section className="rounded-3xl border border-[#ead8ce] bg-[#fffaf7] p-5 lg:p-6"><div className="flex items-center gap-2"><AlertTriangle className="size-5 text-[#a4512e]" /><h2 className="font-semibold text-[#172033]">Atenção agora</h2></div><p className="mt-1 text-sm text-[#704435]">Campanhas com baixa adesão que podem precisar de reforço.</p>{alertas.length ? <div className="mt-5 space-y-3">{alertas.map((campanha) => <article key={campanha.id} className="rounded-2xl border border-[#ead8ce] bg-white p-4"><p className="font-semibold text-[#172033]">{campanha.nome}</p><p className="mt-1 text-sm text-[#687086]">{campanha.indicadores.taxaResposta}% de resposta em {campanha.indicadores.convites} convite{campanha.indicadores.convites === 1 ? "" : "s"}.</p><Link href="/campanhas" className="mt-3 inline-flex items-center gap-1 text-sm font-semibold text-[#8b5a46]">Ver campanha <ArrowRight className="size-3.5" /></Link></article>)}</div> : <div className="mt-5 rounded-2xl bg-white p-5 text-center"><CheckCircle2 className="mx-auto size-6 text-emerald-600" /><p className="mt-2 font-semibold text-[#172033]">Nenhum alerta crítico</p><p className="mt-1 text-sm text-[#687086]">As campanhas com convites estão acima da faixa de atenção.</p></div>}</section></div>
    <section className="surface p-5 lg:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-semibold text-[#172033]">Campanhas recentes</h2><p className="mt-1 text-sm text-[#687086]">Acompanhe a coleta e avance rapidamente para as ações certas.</p></div><Link href="/campanhas" className="inline-flex items-center gap-1 text-sm font-semibold text-[#8b5a46]">Ver todas <ArrowRight className="size-3.5" /></Link></div>{campanhas.length ? <div className="mt-5 overflow-hidden rounded-2xl border border-[#e6e9f0]"><div className="hidden grid-cols-[1.5fr_.7fr_.8fr_.8fr] gap-4 border-b border-[#e6e9f0] bg-[#fafbfe] px-5 py-3 text-xs font-bold uppercase tracking-wide text-[#8a92a4] md:grid"><span>Campanha</span><span>Status</span><span>Participação</span><span className="text-right">Prazo</span></div>{campanhas.slice(0, 5).map((campanha) => <article key={campanha.id} className="grid gap-3 border-b border-[#edf0f5] px-5 py-4 last:border-0 md:grid-cols-[1.5fr_.7fr_.8fr_.8fr] md:items-center"><div><p className="font-semibold text-[#172033]">{campanha.nome}</p><p className="mt-1 text-xs text-[#8a92a4]">{campanha.versao?.questionario?.nome || "Questionário"}</p></div><div><StatusBadge value={campanha.status} /></div><div><p className="font-semibold text-[#172033]">{campanha.indicadores.taxaResposta}%</p><p className="text-xs text-[#8a92a4]">{campanha.indicadores.respondidas} respostas</p></div><div className="flex items-center gap-1.5 text-sm text-[#687086] md:justify-end">{campanha.encerraEm ? <><CalendarDays className="size-4" />{new Date(campanha.encerraEm).toLocaleDateString("pt-BR")}</> : "Sem prazo"}</div></article>)}</div> : !loading && <div className="mt-5"><EmptyState title="Nenhuma campanha criada" description="Crie sua primeira campanha para acompanhar resultados por aqui." action={<Link href="/campanhas" className={`${button} bg-[#5d3a2e] text-white hover:bg-[#4e3026]`}>Criar campanha</Link>} /></div>}</section>
  </div></AppShell>
}
